// Glossary data
export interface GlossaryEntry {
  term: string
  definition: string
  language: 'French' | 'German' | 'Italian' | 'Abbreviation'
}

export const GLOSSARY: GlossaryEntry[] = [
  // FRENCH
  { term: "à 2, à deux", definition: "1. Two instrs that normally play separate parts to play in unison. 2. Two or more instrs that normally play in unison to divide to play separate parts.", language: "French" },
  { term: "abandonné", definition: "Negligent; free and easy.", language: "French" },
  { term: "accoupler", definition: "To couple (in organ music). So accouplé, coupled; accouplement, coupling, coupler (nouns); accouplez, couple (imperative).", language: "French" },
  { term: "à deux cordes", definition: "On 2 strings.", language: "French" },
  { term: "à deux mains", definition: "For 2 hands.", language: "French" },
  { term: "à deux temps", definition: "In 2/2 time.", language: "French" },
  { term: "agilement", definition: "In an agile manner, implying speed and nimble execution.", language: "French" },
  { term: "agilité", definition: "Agility.", language: "French" },
  { term: "agité", definition: "Agitated, in an agitated manner.", language: "French" },
  { term: "à la corde", definition: "At the string. Indication that the bow should be kept on the str, to ensure legato movement from note to note.", language: "French" },
  { term: "à la mesure", definition: "Same as a tempo.", language: "French" },
  { term: "à la pointe d'archet", definition: "At the point of the bow.", language: "French" },
  { term: "allant", definition: "1. Going, i.e. active, brisk. 2. Continuing, e.g. Debussy's allant grandissant—going on growing, continuing to grow (i.e. getting louder).", language: "French" },
  { term: "allègrement", definition: "Brightly.", language: "French" },
  { term: "animé", definition: "Animated.", language: "French" },
  { term: "arraché", definition: "Torn. Extreme form of pizzicato.", language: "French" },
  { term: "articulé", definition: "Well-articulated.", language: "French" },
  { term: "assez", definition: "Enough, fairly; e.g. assez vite, fairly quick.", language: "French" },
  { term: "avec le bois d'archet", definition: "Play with the wood of the bow.", language: "French" },
  { term: "à volonté", definition: "At one's own pleasure; same as ad libitum.", language: "French" },
  { term: "battre", definition: "To beat.", language: "French" },
  { term: "battre à deux temps", definition: "To beat 2 in a measure.", language: "French" },
  { term: "bouche fermée", definition: "Closed-mouth singing; humming (in choral music).", language: "French" },
  { term: "bouchés, sons", definition: "Stopped notes in horn playing.", language: "French" },
  { term: "capricieux", definition: "Capricious; in a lively, informal, whimsical style.", language: "French" },
  { term: "cédez", definition: "Give way; diminish the speed. Present and past participles cédant, cédé.", language: "French" },
  { term: "chantant", definition: "In a singing style. Past participle chanté.", language: "French" },
  { term: "corde à jour, corde à vide", definition: "Open string.", language: "French" },
  { term: "cuivré", definition: "Brassy; (in hn music, etc.) tones are to be forced, with a harsh, ringing timbre.", language: "French" },
  { term: "décidé", definition: "Decided. With decision (i.e. firmly, not flabbily).", language: "French" },
  { term: "dehors", definition: "Prominent; a melody that the composer intends to be particularly prominent.", language: "French" },
  { term: "délié", definition: "Untied. 1. The notes separated from each other; staccato. 2. Unconstrained in style. 3. Supple (fingers).", language: "French" },
  { term: "démancher", definition: "1. To move the left hand along the neck of a str instr. 2. To move the left hand closer to the bridge of a str instr.", language: "French" },
  { term: "demi-jeu", definition: "Half-play; at half power (in organ and harmonium music, etc.).", language: "French" },
  { term: "demi-voix", definition: "Half voice; half the vocal power.", language: "French" },
  { term: "détaché", definition: "Detached; staccato.", language: "French" },
  { term: "détaché sec", definition: "Hammered; see martelé.", language: "French" },
  { term: "doux, douce", definition: "Sweet, gentle. doucement, sweetly, gently.", language: "French" },
  { term: "enchaînez", definition: "Chain together, join up; next movement to be played without break.", language: "French" },
  { term: "en dehors", definition: "From the outside.", language: "French" },
  { term: "enlevez", definition: "Take up; remove (e.g. pedal or mute).", language: "French" },
  { term: "étouffer", definition: "To stifle; to damp, e.g. with vn mute, pf pedal, etc.", language: "French" },
  { term: "facile", definition: "Easy. facilement Easily; fluently and without an effect of striving.", language: "French" },
  { term: "fermer", definition: "To close. In organ music may mean: 1. Close the swell box. 2. Put a particular stop out of action.", language: "French" },
  { term: "fin", definition: "End.", language: "French" },
  { term: "grand détaché", definition: "Staccato with a full bow for each note.", language: "French" },
  { term: "grave", definition: "Slow and solemn.", language: "French" },
  { term: "lent", definition: "Slow. So lentement, slowly; lenteur, slowness.", language: "French" },
  { term: "lié", definition: "Bound. 1. Slurred. 2. Tied.", language: "French" },
  { term: "martelé", definition: "Hammered. Manner of playing bowed instrs by a series of short, sharp blows with the bow upon the str.", language: "French" },
  { term: "modéré", definition: "Restrained, moderate; same as moderato.", language: "French" },
  { term: "ôter", definition: "To take off; discontinue use of a stop (organ music); ôtez les sourdines, take off the mutes.", language: "French" },
  { term: "pas trop vite", definition: "Not too fast.", language: "French" },
  { term: "petit détaché", definition: "Staccato with the point of the bow for each note.", language: "French" },
  { term: "piqué", definition: "Pricked; same as spiccato.", language: "French" },
  { term: "plaqué", definition: "Non-arpeggiated; notes of a chord should be played simultaneously.", language: "French" },
  { term: "posément", definition: "Steadily, sedately.", language: "French" },
  { term: "pressant", definition: "Pressing on; accelerando.", language: "French" },
  { term: "restez", definition: "Remain. 1. Linger on a note rather than hurry off it. 2. In str music, remain in the same position for the duration of a passage.", language: "French" },
  { term: "retenant, retenu", definition: "Holding back, held back (immediately, like ritenuto, not gradually, like rallentando).", language: "French" },
  { term: "sautillé", definition: "Springing; type of bowing with the bow lightly rebounding off the str; like spiccato.", language: "French" },
  { term: "sec", definition: "Dry. 1. Note to be played and released sharply. 2. In perc playing, indication that the note should be damped.", language: "French" },
  { term: "séparé", definition: "Separated; uncoupled (organ music).", language: "French" },
  { term: "se perdant", definition: "Losing oneself; gradually dying away.", language: "French" },
  { term: "serré", definition: "Tightened; with increasing tension and speed. Same as stringendo.", language: "French" },
  { term: "sonore", definition: "Sonorous; so sonorité, sonority.", language: "French" },
  { term: "soutenu", definition: "Sustained; notes must be sustained to their full value in a smooth flow.", language: "French" },
  { term: "supprimez", definition: "Suppress; in organ music, to put out of use the stop in question.", language: "French" },
  { term: "sur la touche", definition: "On the fingerboard; (in str music) bow over the fingerboard. Same as sul tasto.", language: "French" },
  { term: "sur le chevalet", definition: "On the bridge; (in str music) bow on or near the bridge. Same as sul ponticello.", language: "French" },
  { term: "un peu", definition: "A little (often in the sense of 'rather').", language: "French" },

  // GERMAN
  { term: "ab", definition: "Off. In organ music, applied to a stop no longer required.", language: "German" },
  { term: "abdämpfen", definition: "To damp off; to mute, especially in connection with timp.", language: "German" },
  { term: "ablösen", definition: "To loosen from one another. Various applications, e.g. to separate the notes (i.e. to play staccato).", language: "German" },
  { term: "abnehmend", definition: "Off-taking; diminuendo.", language: "German" },
  { term: "abstossen", definition: "1. To detach notes from one another; to play staccato. 2. In organ playing, to cease to use a stop.", language: "German" },
  { term: "abwechseln, abzuwechseln", definition: "To change. Used of orch instr alternating with another in the hands of the same player.", language: "German" },
  { term: "Acht", definition: "Care.", language: "German" },
  { term: "affektvoll", definition: "Full of fervour.", language: "German" },
  { term: "agitirt, agitiert", definition: "Agitated, in an agitated manner.", language: "German" },
  { term: "alle", definition: "All. Thus if one vn has been playing alone all are now to enter.", language: "German" },
  { term: "als", definition: "As, like, when, than.", language: "German" },
  { term: "am", definition: "At the, on the, to the, by the, near the.", language: "German" },
  { term: "am frosch", definition: "At the frog; at the nut of the bow (in string playing).", language: "German" },
  { term: "am Steg", definition: "On the bridge (of vn, etc.); same as sul ponticello.", language: "German" },
  { term: "an", definition: "On, by, to, at; in organ music it signifies that the stop in question is to be drawn.", language: "German" },
  { term: "an der Spitze", definition: "At the point (of the bow).", language: "German" },
  { term: "Anfang", definition: "Beginning. Anfangs At the beginning.", language: "German" },
  { term: "anreissen", definition: "To tear at; use a very forceful pizzicato.", language: "German" },
  { term: "auf", definition: "On, etc. e.g. auf der G, on the G (string).", language: "German" },
  { term: "Auf der Mitte des Bogen", definition: "In the middle of the bow.", language: "German" },
  { term: "aufschwung", definition: "Up-soaring, flight, e.g. mit aufschwung, in a lofty (impassioned) spirit.", language: "German" },
  { term: "Ausdruck", definition: "Expression. Ausdrucksvoll, expressively.", language: "German" },
  { term: "ausgehalten", definition: "Held out; sustained.", language: "German" },
  { term: "aushalten", definition: "To hold out; to sustain.", language: "German" },
  { term: "bebend", definition: "Trembling; tremolo.", language: "German" },
  { term: "bebung", definition: "Trembling. Tremolo effect obtained by a rapid shaking movement of the finger.", language: "German" },
  { term: "bereite vor", definition: "Make ready, prepare (an organ stop).", language: "German" },
  { term: "bestimmt", definition: "1. Decided (in style). 2. Prominent.", language: "German" },
  { term: "beweglichkeit", definition: "Agility.", language: "German" },
  { term: "bewegter", definition: "Quicker.", language: "German" },
  { term: "bleibt", definition: "Remains. In organ music, the stop in question is to remain in use.", language: "German" },
  { term: "breit", definition: "Broad. Sometimes the equivalent of largo, and sometimes applied to bowing.", language: "German" },
  { term: "dämpfung", definition: "Muting, or (piano) soft-pedalling.", language: "German" },
  { term: "dazu", definition: "Thereto; (in organ playing) the stops mentioned are now to be added to the others.", language: "German" },
  { term: "drängend", definition: "Urging forward, hurrying.", language: "German" },
  { term: "durchdringen", definition: "Through-forcing; penetrating, shrill.", language: "German" },
  { term: "durchweg", definition: "1. Throughout, altogether. 2. Generally, nearly always.", language: "German" },
  { term: "ein Takt wie vorher zwei", definition: "1 beat as previously 2; 1 beat allowed as much time as 2 beats previously.", language: "German" },
  { term: "Empfindung", definition: "Feeling, sentiment; hence empfindungsvoll, feelingly.", language: "German" },
  { term: "erniedrigen", definition: "To lower (pitch).", language: "German" },
  { term: "ersterbend", definition: "Dying away.", language: "German" },
  { term: "erweitert", definition: "Widened, broadened; slower and with steadiness.", language: "German" },
  { term: "etwas", definition: "Some, something, somewhat.", language: "German" },
  { term: "feierlich", definition: "Solemn (for religious occasions), festive (for secular).", language: "German" },
  { term: "fliessend", definition: "Flowing. Fliessender, more flowing.", language: "German" },
  { term: "ganzer Bogen", definition: "Whole bow.", language: "German" },
  { term: "gänzlich", definition: "Completely.", language: "German" },
  { term: "gedämpft", definition: "Damped. When applied to str and brass instrs, it means 'muted'; to drums, 'muffled'; and to pf, 'soft-pedalled'.", language: "German" },
  { term: "gehend", definition: "Going; same as andante.", language: "German" },
  { term: "gewöhnlich", definition: "Usual; countermands previous indication that the instr concerned was to be played in some unusual way.", language: "German" },
  { term: "gezogen", definition: "Drawn. 1. Drawn out, sustained. 2. Same as portamento.", language: "German" },
  { term: "hüpfend", definition: "Hopping; same as spiccato.", language: "German" },
  { term: "hurtig", definition: "Nimble, quick; same as allegro.", language: "German" },
  { term: "im Takt", definition: "In time; same as a tempo.", language: "German" },
  { term: "kneifend", definition: "Plucking; same as pizzicato.", language: "German" },
  { term: "langsam", definition: "Slow. Langsamer, slower.", language: "German" },
  { term: "leer", definition: "Empty; open (as in strings of vn, etc.).", language: "German" },
  { term: "leise", definition: "Soft, gentle. Leiser, softer.", language: "German" },
  { term: "luftig", definition: "Airy.", language: "German" },
  { term: "mächtig", definition: "Mighty, powerful.", language: "German" },
  { term: "Mal", definition: "Time, in such contexts as Erste Mal, 1st time; 2 Mal (Zweimal), twice, etc.", language: "German" },
  { term: "markiert", definition: "Marked; clearly accented, or brought out (e.g. the tune, etc.).", language: "German" },
  { term: "markig", definition: "Vigorous. Directive frequently found in Bruckner scores.", language: "German" },
  { term: "mässig", definition: "1. Moderate, moderately. 2. In the style of (e.g. marschmässig, in march style).", language: "German" },
  { term: "mit Affekt", definition: "With warmth or passion.", language: "German" },
  { term: "mit aufschwung", definition: "In a lofty (impassioned) spirit.", language: "German" },
  { term: "mit Dämpfern", definition: "With mutes.", language: "German" },
  { term: "nach", definition: "After, in the manner of, according to, towards, to.", language: "German" },
  { term: "nach und nach", definition: "Bit by bit.", language: "German" },
  { term: "nach Wunsch", definition: "According to one's wish; same as ad libitum.", language: "German" },
  { term: "Natürlich", definition: "Natural; return to a natural style of performing. Same as naturale.", language: "German" },
  { term: "Piquiren", definition: "To play spiccato.", language: "German" },
  { term: "plötzlich", definition: "Suddenly.", language: "German" },
  { term: "rasch, rascher", definition: "Quick, quicker.", language: "German" },
  { term: "scharf", definition: "Sharply. Schärfe, sharpness, definiteness, precision.", language: "German" },
  { term: "Scharf betont", definition: "Given out with emphatic accent.", language: "German" },
  { term: "scherzend, scherzhaft", definition: "Jocular.", language: "German" },
  { term: "schleppend", definition: "Dragging. Often found in Mahler's scores in the negative, i.e. nicht schleppend.", language: "German" },
  { term: "schmachtend", definition: "Yearning, longing.", language: "German" },
  { term: "schnell, schneller", definition: "Quick, quicker. Schnelligkeit, speed.", language: "German" },
  { term: "schweigt", definition: "Tacet.", language: "German" },
  { term: "schwer", definition: "1. Heavy (in style). 2. Difficult. Schwermütig, heavy-hearted.", language: "German" },
  { term: "schwindend", definition: "Diminishing (in volume of tone); diminuendo.", language: "German" },
  { term: "spielend", definition: "Playing, playful.", language: "German" },
  { term: "stark", definition: "Strong, loud. So stärker, stronger, louder.", language: "German" },
  { term: "stark anblasen, stark blasend", definition: "Strongly blown (wind instrs).", language: "German" },
  { term: "sterbend", definition: "Dying away.", language: "German" },
  { term: "taktfest", definition: "Time-firm; in steady time.", language: "German" },
  { term: "Takt halten", definition: "To hold (keep) time.", language: "German" },
  { term: "taktmässig", definition: "Time moderated; generally the same as tempo comodo.", language: "German" },
  { term: "tempo wie vorher", definition: "Resume original speed; same as tempo primo.", language: "German" },
  { term: "verdoppeln", definition: "To double. Verdoppelt, doubled; verdoppelung, doubling.", language: "German" },
  { term: "verhallend", definition: "Dying away.", language: "German" },
  { term: "verlierend", definition: "Losing itself; dying away.", language: "German" },
  { term: "verlöschend", definition: "Extinguished; dying away.", language: "German" },
  { term: "verschiebung", definition: "Shoving away. Soft pedal.", language: "German" },
  { term: "verschwindend", definition: "Disappearing; dying away.", language: "German" },
  { term: "Volles Spiel", definition: "Full organ.", language: "German" },
  { term: "Vom Anfang", definition: "Repeat from the beginning.", language: "German" },
  { term: "Wie anfänglich", definition: "As at the beginning.", language: "German" },
  { term: "ziehen", definition: "To draw out.", language: "German" },
  { term: "zitternd", definition: "Trembling; same as tremolando.", language: "German" },
  { term: "zu 2", definition: "1. 2 instruments to play the same part. 2. All the instrs in question to divide into 2 parts.", language: "German" },
  { term: "zurückgehend", definition: "Going back (i.e. to orig. tempo).", language: "German" },
  { term: "zurückhaltend", definition: "Holding back; same as rallentando.", language: "German" },

  // ITALIAN
  { term: "a 2", definition: "1. Two instrs that normally play separate parts to play in unison. 2. Two or more instrs that normally play in unison to divide to play separate parts.", language: "Italian" },
  { term: "a battuta", definition: "With the beat; return to strict tempo.", language: "Italian" },
  { term: "abbandono", definition: "Abandon; free, impassioned style.", language: "Italian" },
  { term: "abbassare", definition: "To lower; to tune down a str of an instr of the vn family.", language: "Italian" },
  { term: "accarezzevole, accarezzevolmente", definition: "Caressing, caressingly.", language: "Italian" },
  { term: "accentato", definition: "Accented.", language: "Italian" },
  { term: "acciaccato", definition: "Broken down, crushed; the sounding of the notes of a chord not quite simultaneously, but from bottom to top.", language: "Italian" },
  { term: "accoppiare", definition: "To couple (in organ music). Hence accoppiato, coupled; accoppiamento, coupling.", language: "Italian" },
  { term: "adagietto", definition: "Slow, but less so than adagio.", language: "Italian" },
  { term: "adagio", definition: "At ease. Slow (not so slow as largo, but slower than andante).", language: "Italian" },
  { term: "adagio assai", definition: "Very slow.", language: "Italian" },
  { term: "adagissimo", definition: "Extremely slow.", language: "Italian" },
  { term: "addolcendo", definition: "Becoming dolce (gentle or sweet).", language: "Italian" },
  { term: "addolorato", definition: "Grieved; in a saddened style.", language: "Italian" },
  { term: "a due", definition: "1. Divide between 2 instruments or voices. 2. 2 instruments or voices join in playing the same line.", language: "Italian" },
  { term: "a due corde", definition: "On 2 strings (in music for str instrs).", language: "Italian" },
  { term: "affettuoso, affettuosa", definition: "Affectionate, with tenderness.", language: "Italian" },
  { term: "affettuosamente", definition: "Affectionately.", language: "Italian" },
  { term: "affezione", definition: "Affection.", language: "Italian" },
  { term: "affretando", definition: "Hurrying, quickening; increase tempo, implying also an increase in nervous energy.", language: "Italian" },
  { term: "aggiustamente", definition: "Exact (in point of rhythm).", language: "Italian" },
  { term: "agiatamente", definition: "Comfortably, freely; with suitable liberty as regards speed.", language: "Italian" },
  { term: "agilmente", definition: "In an agile manner, implying speed and nimble execution. Agilità — Agility.", language: "Italian" },
  { term: "agitato", definition: "Agitated, in an agitated manner. Agitazione — Agitation.", language: "Italian" },
  { term: "al", definition: "At the, to the, in the, in the style of.", language: "Italian" },
  { term: "alla breve", definition: "Indicates 2/2 time when, in a measure of 4 beats, the tempo is so fast that the measure may be considered to have 2 beats.", language: "Italian" },
  { term: "allargando", definition: "Enlarging; getting slower and broadening, without loss of fullness in tone.", language: "Italian" },
  { term: "alla tedesca", definition: "In the German style.", language: "Italian" },
  { term: "allegramente", definition: "Brightly.", language: "Italian" },
  { term: "allegretto", definition: "Moderately quick, pretty lively (but not so much as allegro).", language: "Italian" },
  { term: "allegrezza", definition: "Mirth, cheerfulness.", language: "Italian" },
  { term: "allegro", definition: "Merry; i.e. quick, lively, bright.", language: "Italian" },
  { term: "allegrissimo", definition: "Superlative of allegro.", language: "Italian" },
  { term: "allentamento, allentando", definition: "Slowing down.", language: "Italian" },
  { term: "al loco", definition: "At the place; return to octave as written.", language: "Italian" },
  { term: "amoroso", definition: "Loving, affectionate.", language: "Italian" },
  { term: "andante", definition: "From andare, to go. Moving along, flowing (slowish but not slow).", language: "Italian" },
  { term: "andantino", definition: "A diminution of andante. Commonly accepted as a little quicker than andante.", language: "Italian" },
  { term: "andante cantabile", definition: "Flowing and songlike.", language: "Italian" },
  { term: "andante spianato", definition: "Flowing and smooth.", language: "Italian" },
  { term: "animandosi", definition: "Becoming animated. Animato — animated.", language: "Italian" },
  { term: "aperto", definition: "Open. 1. Clear, distinct. 2. Broad in style.", language: "Italian" },
  { term: "appassionato", definition: "Impassioned; so appassionatamente, passionately.", language: "Italian" },
  { term: "appoggiando, appoggiato", definition: "Leaning; leaned. 1. Each note passing very smoothly to the next (portamento). 2. Stressed.", language: "Italian" },
  { term: "a punta d'arco", definition: "At the point of the bow (in str playing).", language: "Italian" },
  { term: "arcata", definition: "Stroke of bow (in str playing), often followed by in giù (down), or in su (up).", language: "Italian" },
  { term: "arcato", definition: "Bowed (used after a passage of pizzicato).", language: "Italian" },
  { term: "arco", definition: "Bow (used after a passage of pizzicato).", language: "Italian" },
  { term: "arpeggiare", definition: "To play chords as arpeggios. Present and past participles, arpeggiando, arpeggiato.", language: "Italian" },
  { term: "articolato", definition: "Well-articulated.", language: "Italian" },
  { term: "assai", definition: "Very, extremely.", language: "Italian" },
  { term: "a tempo", definition: "In time; resume original speed.", language: "Italian" },
  { term: "attacca", definition: "Attack (imperative); start the next movement without a break. Also attacco subito.", language: "Italian" },
  { term: "ballabile", definition: "In a dance style.", language: "Italian" },
  { term: "bocca chiusa", definition: "Closed mouth; a wordless humming (in choral music).", language: "Italian" },
  { term: "brio", definition: "Vigour, spirit, fire. Adjective brioso.", language: "Italian" },
  { term: "burlando", definition: "Jestingly.", language: "Italian" },
  { term: "cadenzato", definition: "Cadenced; rhythmic.", language: "Italian" },
  { term: "calando", definition: "Lowering. Diminuendo, with also rallentando.", language: "Italian" },
  { term: "calcando", definition: "Trampling; much the same as accelerando.", language: "Italian" },
  { term: "calmato, calmando", definition: "Calmed, calming.", language: "Italian" },
  { term: "calore", definition: "Heat. Passion. So the adjective caloroso.", language: "Italian" },
  { term: "cantabile", definition: "Singingly.", language: "Italian" },
  { term: "capriccioso", definition: "Capricious; in a lively, informal, whimsical style. Adverb capricciosamente.", language: "Italian" },
  { term: "carezzando, carezzevole", definition: "Caressing, caressingly.", language: "Italian" },
  { term: "celere", definition: "Quick, speedy, hence celerità, speed.", language: "Italian" },
  { term: "chiuso, chiusa", definition: "Closed, stopped, with special reference to the horn.", language: "Italian" },
  { term: "col, coll', colla, colle", definition: "With the, e.g. col basso, with the bass; colla voce, with the voice.", language: "Italian" },
  { term: "col canto", definition: "With the song; the acc. to take his tempos from the perf of the melody.", language: "Italian" },
  { term: "colla parte", definition: "With the part.", language: "Italian" },
  { term: "colla punta dell' arco", definition: "With the point of the bow.", language: "Italian" },
  { term: "coll'arco", definition: "With the bow (used after a passage of pizzicato).", language: "Italian" },
  { term: "colla voce", definition: "With the voice; the acc. to take his tempos from the soloist.", language: "Italian" },
  { term: "col legno", definition: "With the wood; striking the str with the stick of the bow.", language: "Italian" },
  { term: "come", definition: "As, like, as if. Come prima, as at first; come stà, as it stands.", language: "Italian" },
  { term: "comodo", definition: "Leisurely, convenient; without any suspicion of strain.", language: "Italian" },
  { term: "con anima", definition: "With feeling.", language: "Italian" },
  { term: "con brio", definition: "Spiritedly.", language: "Italian" },
  { term: "con fuoco", definition: "With a combination of force and speed.", language: "Italian" },
  { term: "con moto", definition: "With motion; quickly.", language: "Italian" },
  { term: "con slancio", definition: "With impetuosity.", language: "Italian" },
  { term: "coperti", definition: "Covered; used of drums muted by being covered with a cloth.", language: "Italian" },
  { term: "corda vuota", definition: "Empty string; open str (in music for str instrs).", language: "Italian" },
  { term: "cupo", definition: "Dark, sombre.", language: "Italian" },
  { term: "da capo", definition: "From the head; repeat from the beginning.", language: "Italian" },
  { term: "dal niente", definition: "To nothing; fade out to nothing.", language: "Italian" },
  { term: "deciso", definition: "Decided. With decision (i.e. firmly, not flabbily).", language: "Italian" },
  { term: "delicato", definition: "Delicate. So delicatamente, delicately; delicatezza, delicacy.", language: "Italian" },
  { term: "delirante", definition: "Frenzied.", language: "Italian" },
  { term: "diluendo", definition: "Dissolving; dying away.", language: "Italian" },
  { term: "di molto", definition: "Of much; very. Augments the word to which it is applied, e.g. allegro di molto, very fast.", language: "Italian" },
  { term: "dolce", definition: "Sweet (also with the implication of 'soft') or gentle. Hence dolcissimo, very sweet; dolcezza, sweetness.", language: "Italian" },
  { term: "dolente", definition: "Doleful, sorrowful.", language: "Italian" },
  { term: "dolore", definition: "Sorrow, dolour, pain. Hence doloroso, dolorous.", language: "Italian" },
  { term: "doppio movimento", definition: "Double movement; at twice the preceding speed.", language: "Italian" },
  { term: "elegiaco", definition: "Elegiac.", language: "Italian" },
  { term: "energia", definition: "Energy. Energico, energetic.", language: "Italian" },
  { term: "espressione", definition: "Expression. Espressivo, expressively.", language: "Italian" },
  { term: "estinguendo", definition: "Extinguishing; dying away.", language: "Italian" },
  { term: "estinto", definition: "Extinct; as soft as possible.", language: "Italian" },
  { term: "facilmente", definition: "Fluently and without an effect of striving.", language: "Italian" },
  { term: "focoso", definition: "Fiery.", language: "Italian" },
  { term: "forte", definition: "Strong; loud. Fortissimo, very loudly.", language: "Italian" },
  { term: "furia", definition: "Fury. So furioso, furibondo, furious.", language: "Italian" },
  { term: "giocoso", definition: "Jocose, merry, playful. Adverb giocosamente.", language: "Italian" },
  { term: "gioia", definition: "Joy. So gioiante, gioioso; gioiosamente, joyful.", language: "Italian" },
  { term: "giustamente", definition: "With exactitude; unvarying speed and rhythm.", language: "Italian" },
  { term: "giusto", definition: "Just, strict. Thus allegro giusto, a strict allegro or a moderate allegro.", language: "Italian" },
  { term: "grandezza", definition: "Grandeur, dignity.", language: "Italian" },
  { term: "grandioso", definition: "With dignity.", language: "Italian" },
  { term: "grave", definition: "Slow and solemn.", language: "Italian" },
  { term: "in modo di", definition: "In the manner of.", language: "Italian" },
  { term: "lacrimoso, lagrimoso", definition: "Lachrymose, tearful.", language: "Italian" },
  { term: "largamente", definition: "Broadly; slowish and dignified.", language: "Italian" },
  { term: "largo", definition: "Broad; slow, dignified in style. Diminutive larghetto.", language: "Italian" },
  { term: "legato", definition: "Bound together; in a smooth manner.", language: "Italian" },
  { term: "legg(i)eramente", definition: "Lightly. legg(i)erezza — lightness; leggerissimo, as light as possible.", language: "Italian" },
  { term: "leggiadramente", definition: "Gracefully.", language: "Italian" },
  { term: "lento", definition: "Slow. So lentamente, slowly; lentezza, slowness; lentissimo, very slow.", language: "Italian" },
  { term: "lesto", definition: "Quick. So lestamente, quickly; lestissimo, very quickly.", language: "Italian" },
  { term: "levare", definition: "To lift, or take off (pedal, mute, etc.).", language: "Italian" },
  { term: "liberamente", definition: "Freely (with regard to tempo, rhythm, etc.).", language: "Italian" },
  { term: "licenza", definition: "Licence, freedom.", language: "Italian" },
  { term: "l'istesso tempo", definition: "The same speed; retain the same duration of the beat even though its nominal value may have changed.", language: "Italian" },
  { term: "loco", definition: "Place; return to the octave as written.", language: "Italian" },
  { term: "lusingando", definition: "Flattering; play in a coaxing, intimate manner.", language: "Italian" },
  { term: "lutto", definition: "Mourning. So luttoso or luttuoso, mournful.", language: "Italian" },
  { term: "maestoso", definition: "Majestic, dignified.", language: "Italian" },
  { term: "ma non troppo", definition: "But not too much.", language: "Italian" },
  { term: "marcando, marcato", definition: "Marking, marked; each note emphasized. Superlative is marcatissimo.", language: "Italian" },
  { term: "marcato il canto", definition: "Bring out the tune.", language: "Italian" },
  { term: "martellando, martellato", definition: "Hammered. Same as martelé.", language: "Italian" },
  { term: "marziale", definition: "Martial.", language: "Italian" },
  { term: "medesimo", definition: "Same, e.g. medesimo movimento, the same speed.", language: "Italian" },
  { term: "mezza voce", definition: "Half voice; half the vocal power.", language: "Italian" },
  { term: "meno", definition: "Less, as in meno mosso, less moved, i.e. slower.", language: "Italian" },
  { term: "mesto", definition: "Mournful, sad. So mestizia — Sadness.", language: "Italian" },
  { term: "minaccevole, minaccevolmente", definition: "Menacing, menacingly.", language: "Italian" },
  { term: "mistero", definition: "Mystery. Misterioso, mysteriously.", language: "Italian" },
  { term: "moderato", definition: "Restrained, moderate.", language: "Italian" },
  { term: "molto", definition: "Much, very, e.g. allegro molto, very quickly.", language: "Italian" },
  { term: "morbido", definition: "Soft, gentle; morbidezza, softness, gentleness.", language: "Italian" },
  { term: "morendo", definition: "Dying; fade away gradually.", language: "Italian" },
  { term: "muta", definition: "Change, e.g. muta D in C, change tuning from D to C (in timpani music).", language: "Italian" },
  { term: "naturale", definition: "Natural; return to a natural style after performing in some unusual way.", language: "Italian" },
  { term: "niente", definition: "Nothing; used to indicate that the sound is gradually to fade out of hearing.", language: "Italian" },
  { term: "nobilmente", definition: "Nobly, in a noble style.", language: "Italian" },
  { term: "non vibrato", definition: "Without vibrato.", language: "Italian" },
  { term: "ondeggiando", definition: "Undulating; tremolo, vibrato or any swaying effect.", language: "Italian" },
  { term: "ossia", definition: "Or else; an alternative version of a music passage.", language: "Italian" },
  { term: "parlando, parlante", definition: "Speaking. 1. In vocal music, tone approximates to speech. 2. In instrumental music, an expressive freedom greater than cantabile.", language: "Italian" },
  { term: "perdendo, perdendosi", definition: "Losing oneself; gradually dying away.", language: "Italian" },
  { term: "pesante", definition: "Heavy or heavily.", language: "Italian" },
  { term: "piacevole", definition: "Agreeable.", language: "Italian" },
  { term: "piangendo, piangente", definition: "Weeping. Piangevole, piangevolmente, plaintive, plaintively.", language: "Italian" },
  { term: "piano", definition: "Soft, quiet. Pianissimo, very softly.", language: "Italian" },
  { term: "picchettato", definition: "Knocked, knocking; detaching the notes (for bowed str instrs).", language: "Italian" },
  { term: "più", definition: "More.", language: "Italian" },
  { term: "più mosso", definition: "More moved; quicker.", language: "Italian" },
  { term: "poco", definition: "A little, rather. Pochissimo, the least possible.", language: "Italian" },
  { term: "poco a poco", definition: "Little by little.", language: "Italian" },
  { term: "poco meno mosso", definition: "A little less moved; a little slower.", language: "Italian" },
  { term: "portando, portato", definition: "Carrying, carried; see portamento.", language: "Italian" },
  { term: "precipitato, precipitoso", definition: "Rushed; impetuously.", language: "Italian" },
  { term: "pressando, pressante", definition: "Pressing on; accelerando.", language: "Italian" },
  { term: "presto", definition: "Quick. Prestezza, quickness; prestissimo, very quick.", language: "Italian" },
  { term: "rallentando", definition: "Slowing down, gradually. Virtually the same as ritardando.", language: "Italian" },
  { term: "ravvivando", definition: "Reviving, brightening up; quickening.", language: "Italian" },
  { term: "resoluto, risoluto", definition: "Resolute.", language: "Italian" },
  { term: "ritardando", definition: "Holding back, to hold back, held back; same as rallentando.", language: "Italian" },
  { term: "saltando, saltato", definition: "Leaping, leapt. In str playing, with a springing bow; same as spiccato.", language: "Italian" },
  { term: "scemando", definition: "Diminishing (in volume of tone); same as diminuendo.", language: "Italian" },
  { term: "scherzoso", definition: "Playful, playfully. Thus scherzando, joking, playful.", language: "Italian" },
  { term: "sciolto", definition: "Untied; in a free and easy manner.", language: "Italian" },
  { term: "scivolando", definition: "Sliding; glissando.", language: "Italian" },
  { term: "segue", definition: "It follows; next section is to follow without a break.", language: "Italian" },
  { term: "semplice", definition: "Simple, simplicity. Semplicemente, simply.", language: "Italian" },
  { term: "sempre", definition: "Always.", language: "Italian" },
  { term: "senza", definition: "Without.", language: "Italian" },
  { term: "senza sordino", definition: "1. Without mute(s) (of str instrs). 2. Use the right pedal (of the pf).", language: "Italian" },
  { term: "sfogato", definition: "Airy, evaporated; light and easy in style.", language: "Italian" },
  { term: "simile", definition: "The same; phrase to be performed in same manner as preceding phrase.", language: "Italian" },
  { term: "slargando", definition: "Slowing, broadening, widening; same as rallentando.", language: "Italian" },
  { term: "smanioso", definition: "Frenzied; with furious excitement.", language: "Italian" },
  { term: "soave", definition: "Suave or gentle. Soavemente, suavely.", language: "Italian" },
  { term: "sonoro", definition: "Sonorous; so sonorità, sonority.", language: "Italian" },
  { term: "sopra una corda", definition: "1. On one string (of vn, etc.) 2. Use the 'soft' pedal (in pf music).", language: "Italian" },
  { term: "sospirando", definition: "Sighing; plaintive in style.", language: "Italian" },
  { term: "sostenuto", definition: "Sustained; notes must be sustained to their full value in a smooth flow.", language: "Italian" },
  { term: "sotto voce", definition: "Below the voice; in an undertone or barely audible.", language: "Italian" },
  { term: "spianato", definition: "Planed, levelled, smoothed.", language: "Italian" },
  { term: "spiccato", definition: "Separated; form of staccato bowing in which the bow is allowed to bounce on the string.", language: "Italian" },
  { term: "spirito", definition: "Spirit, spirited.", language: "Italian" },
  { term: "squillante", definition: "Clanging; applied to cymbals, means they should be suspended and struck with drumsticks.", language: "Italian" },
  { term: "staccato", definition: "Detached; method of playing a note so that it is 'detached' from its successor by being held for less than its full value.", language: "Italian" },
  { term: "stendendo", definition: "Extending; spacing out the notes. Same as rallentando.", language: "Italian" },
  { term: "steso", definition: "Spread out; slow.", language: "Italian" },
  { term: "stinguendo", definition: "Extinguishing; fading out.", language: "Italian" },
  { term: "strascicando", definition: "Dragging, dragged; heavily slurring notes in bowing, singing portamento, etc.", language: "Italian" },
  { term: "strepitoso", definition: "Noisy, loud; play forcefully, with the implication of headlong excitement.", language: "Italian" },
  { term: "stringendo", definition: "Squeezing; increase the intensity of the music by quickening the tempo.", language: "Italian" },
  { term: "strisciando", definition: "Trailing, smooth. Correct Italian term for glissando.", language: "Italian" },
  { term: "subito", definition: "Suddenly. Quickly, immediately.", language: "Italian" },
  { term: "sul ponticello", definition: "On the bridge; (in str music) bow as near as possible to the bridge, producing a metallic but mysterious sound.", language: "Italian" },
  { term: "sul tasto", definition: "On the touch; (in str music) bow over the fingerboard, giving a rich, mellow sound.", language: "Italian" },
  { term: "susurrando", definition: "Whispering.", language: "Italian" },
  { term: "svegliando", definition: "Awakening, awakened; brisk, alert.", language: "Italian" },
  { term: "tanto", definition: "So much, as much, too much. Non tanto, not too much.", language: "Italian" },
  { term: "tardo", definition: "Slow. So tardamente, slowly; tardando, slowing gradually.", language: "Italian" },
  { term: "tasto solo", definition: "Play the key alone; only the bass line, without adding chords (in figured bass).", language: "Italian" },
  { term: "tempo a piacere", definition: "Please yourself what speed.", language: "Italian" },
  { term: "tempo comodo", definition: "At a comfortable, moderate speed.", language: "Italian" },
  { term: "tempo giusto", definition: "In exact time, or at speed the style of the music demands.", language: "Italian" },
  { term: "tempo ordinario", definition: "Ordinary time; at the same speed as before or at a moderate speed.", language: "Italian" },
  { term: "tempo rubato", definition: "In rubato time.", language: "Italian" },
  { term: "tenebroso", definition: "Dark. Gloomy.", language: "Italian" },
  { term: "tenero", definition: "Tender. So teneramente, tenderly; tenerezza, tenderness.", language: "Italian" },
  { term: "tenuto", definition: "Held; hold note to its full value, sometimes even longer.", language: "Italian" },
  { term: "tranquillo", definition: "Tranquil. So tranquillamente, tranquilly.", language: "Italian" },
  { term: "trascinado", definition: "Dragging, holding back; same as rallentando.", language: "Italian" },
  { term: "trattenuto", definition: "1. Held back. 2. Sustained.", language: "Italian" },
  { term: "tre corde", definition: "3 strings. Cancels the term una corde (in pf music).", language: "Italian" },
  { term: "tremolando", definition: "Trembling. With tremolo effect.", language: "Italian" },
  { term: "tremolo", definition: "Shaking, trembling. On str instrs, the rapid reiteration of a note or chord by back-and-forth strokes of the bow.", language: "Italian" },
  { term: "tutti", definition: "All, everybody; all play.", language: "Italian" },
  { term: "una corda", definition: "1. One string. 2. Use the 'soft' pedal (in pf music).", language: "Italian" },
  { term: "uniti", definition: "United; used to revoke a direction such as divisi.", language: "Italian" },
  { term: "un poco (un po')", definition: "A little (often in the sense of 'rather').", language: "Italian" },
  { term: "vibrato", definition: "Vibrated; undulation of pitch produced in str instr by controlled vibration of player's finger and in wind instr by breath-control.", language: "Italian" },
  { term: "vivace", definition: "Vivacious; fast and lively. Vivacissimo, very fast.", language: "Italian" },
  { term: "vivo", definition: "Lively. Vivissimo, very lively.", language: "Italian" },
  { term: "volante", definition: "Flying; swift, light. In vn playing, a bow-stroke in which the bow bounces from the str in a slurred staccato.", language: "Italian" },
  { term: "volta", definition: "Time, in sense of prima volta, 1st time.", language: "Italian" },
  { term: "volti subito", definition: "Turn over (page) at once.", language: "Italian" },

  // ABBREVIATIONS
  { term: "acc.", definition: "Accompanying/accompanied (by)/accompanist", language: "Abbreviation" },
  { term: "accdn", definition: "Accordion", language: "Abbreviation" },
  { term: "arr.", definition: "Arranged (by, for)/arrangement (by, of)", language: "Abbreviation" },
  { term: "b", definition: "Born", language: "Abbreviation" },
  { term: "bar.", definition: "Baritone", language: "Abbreviation" },
  { term: "bass-bar.", definition: "Bass-baritone", language: "Abbreviation" },
  { term: "BBC", definition: "British Broadcasting Corporation", language: "Abbreviation" },
  { term: "bc", definition: "Basso continuo / Before Christ", language: "Abbreviation" },
  { term: "bn", definition: "Bassoon", language: "Abbreviation" },
  { term: "BWV", definition: "Bach Werke-Verzeichnis", language: "Abbreviation" },
  { term: "c.", definition: "Circa (Latin = about)", language: "Abbreviation" },
  { term: "ca", definition: "Cor anglais", language: "Abbreviation" },
  { term: "cel", definition: "Celesta", language: "Abbreviation" },
  { term: "CG", definition: "Covent Garden (Royal Opera House), London", language: "Abbreviation" },
  { term: "cl", definition: "Clarinet", language: "Abbreviation" },
  { term: "cond.", definition: "Conductor (of)/conducted (by)", language: "Abbreviation" },
  { term: "ct", definition: "Countertenor", language: "Abbreviation" },
  { term: "d", definition: "Died", language: "Abbreviation" },
  { term: "D", definition: "Deutsch catalogue number (Schubert works)", language: "Abbreviation" },
  { term: "db", definition: "Double bass", language: "Abbreviation" },
  { term: "ed.", definition: "Editor/edited (by)", language: "Abbreviation" },
  { term: "ENO", definition: "English National Opera", language: "Abbreviation" },
  { term: "euph", definition: "Euphonium", language: "Abbreviation" },
  { term: "fl", definition: "Floruit (Latin = flourished) / Flute", language: "Abbreviation" },
  { term: "f.p.", definition: "First performance(s)/first performed (by, in)", language: "Abbreviation" },
  { term: "glock", definition: "Glockenspiel", language: "Abbreviation" },
  { term: "gui", definition: "Guitar", language: "Abbreviation" },
  { term: "hn", definition: "Horn (French)", language: "Abbreviation" },
  { term: "hp", definition: "Harp", language: "Abbreviation" },
  { term: "hpd", definition: "Harpsichord", language: "Abbreviation" },
  { term: "instr(s)", definition: "Instrument(s)/instrumental", language: "Abbreviation" },
  { term: "K", definition: "Köchel catalogue number (Mozart works)", language: "Abbreviation" },
  { term: "kbd", definition: "Keyboard", language: "Abbreviation" },
  { term: "lib.", definition: "Libretto/library", language: "Abbreviation" },
  { term: "LPO", definition: "London Philharmonic Orchestra", language: "Abbreviation" },
  { term: "LSO", definition: "London Symphony Orchestra", language: "Abbreviation" },
  { term: "mand", definition: "Mandolin", language: "Abbreviation" },
  { term: "mar", definition: "Marimba", language: "Abbreviation" },
  { term: "Met", definition: "Metropolitan Opera House, New York", language: "Abbreviation" },
  { term: "mez.", definition: "Mezzo-soprano", language: "Abbreviation" },
  { term: "movt(s)", definition: "Movement(s)", language: "Abbreviation" },
  { term: "MS(S)", definition: "Manuscript(s)", language: "Abbreviation" },
  { term: "nar", definition: "Narrator", language: "Abbreviation" },
  { term: "ob", definition: "Oboe", language: "Abbreviation" },
  { term: "Op.", definition: "Opus", language: "Abbreviation" },
  { term: "orch", definition: "Orchestra/orchestral", language: "Abbreviation" },
  { term: "ov.", definition: "Overture", language: "Abbreviation" },
  { term: "perc", definition: "Percussion", language: "Abbreviation" },
  { term: "pf", definition: "Pianoforte", language: "Abbreviation" },
  { term: "pic", definition: "Piccolo", language: "Abbreviation" },
  { term: "qnt", definition: "Quintet", language: "Abbreviation" },
  { term: "qt", definition: "Quartet", language: "Abbreviation" },
  { term: "RAM", definition: "Royal Academy of Music, London", language: "Abbreviation" },
  { term: "RCM", definition: "Royal College of Music, London", language: "Abbreviation" },
  { term: "rec", definition: "Recorder", language: "Abbreviation" },
  { term: "rev.", definition: "Revised/revision (by, in, for)", language: "Abbreviation" },
  { term: "ROH", definition: "Royal Opera House, Covent Garden", language: "Abbreviation" },
  { term: "RPO", definition: "Royal Philharmonic Orchestra", language: "Abbreviation" },
  { term: "SATB", definition: "Soprano, alto (contralto), tenor, bass", language: "Abbreviation" },
  { term: "sax", definition: "Saxophone", language: "Abbreviation" },
  { term: "sop.", definition: "Soprano", language: "Abbreviation" },
  { term: "str", definition: "String(s)", language: "Abbreviation" },
  { term: "sym(s).", definition: "Symphony, symphonies", language: "Abbreviation" },
  { term: "synth", definition: "Synthesizer", language: "Abbreviation" },
  { term: "tb", definition: "Trombone", language: "Abbreviation" },
  { term: "ten.", definition: "Tenor", language: "Abbreviation" },
  { term: "timp", definition: "Timpani", language: "Abbreviation" },
  { term: "tpt", definition: "Trumpet", language: "Abbreviation" },
  { term: "trans.", definition: "Translated (by, for)/translation", language: "Abbreviation" },
  { term: "unacc.", definition: "Unaccompanied", language: "Abbreviation" },
  { term: "v., vv.", definition: "Voice, voices", language: "Abbreviation" },
  { term: "var.", definition: "Various/variation(s)", language: "Abbreviation" },
  { term: "vc", definition: "Cello(s)", language: "Abbreviation" },
  { term: "vib", definition: "Vibraphone", language: "Abbreviation" },
  { term: "vla", definition: "Viola(s)", language: "Abbreviation" },
  { term: "vn", definition: "Violin(s)", language: "Abbreviation" },
  { term: "WNO", definition: "Welsh National Opera", language: "Abbreviation" },
  { term: "WoO", definition: "Werk ohne Opuszahl (work without opus number)", language: "Abbreviation" },
  { term: "ww", definition: "Woodwind", language: "Abbreviation" },
  { term: "xyl", definition: "Xylophone", language: "Abbreviation" },
]
