import { Card } from '../types'

export const CM_LEVEL1_CARDS: Card[] = [

  // ── SIGNS AND TERMS (Prep + Level 1) ──
  { id: 101, type: 'text', front: 'a tempo', back: 'Return to the original tempo' },
  { id: 102, type: 'text', front: 'Accent', back: 'With emphasis or stress on a note' },
  { id: 103, type: 'text', front: 'Bar line', back: 'A vertical line that separates notes on the staff into measures' },
  { id: 104, type: 'text', front: 'Bass clef (F clef)', back: 'Names the fourth line of the bass staff — used for lower notes' },
  { id: 105, type: 'text', front: 'Brace', back: 'A wavy line that joins the treble and bass staves of a grand staff' },
  { id: 106, type: 'text', front: 'D.C. al Fine (da capo al fine)', back: 'Return to the beginning, play to Fine (the end)' },
  { id: 107, type: 'text', front: 'Dynamics', back: 'Symbols or terms that indicate loud or soft — variations in volume' },
  { id: 108, type: 'text', front: 'Fermata', back: 'Hold longer — sustain the note beyond its normal value' },
  { id: 109, type: 'text', front: 'Fine', back: 'The end' },
  { id: 110, type: 'text', front: 'Forte (f)', back: 'Loud' },
  { id: 111, type: 'text', front: 'Grand staff', back: 'Two staves joined together by a brace — treble and bass clef combined' },
  { id: 112, type: 'text', front: 'Measure', back: 'The space between two bar lines' },
  { id: 113, type: 'text', front: 'Piano (p)', back: 'Soft' },
  { id: 114, type: 'text', front: 'Repeat sign', back: 'A sign with two dots that indicates a section of music should be repeated' },
  { id: 115, type: 'text', front: 'Ritardando / rit.', back: 'Gradually slower' },
  { id: 116, type: 'text', front: 'Slur', back: 'A curved line connecting two or more different pitches — play smoothly (legato)' },
  { id: 117, type: 'text', front: 'Staccato', back: 'Separated, detached, not connected' },
  { id: 118, type: 'text', front: 'Tie', back: 'A curved line connecting notes of the same pitch — hold for full value, do not re-strike' },
  { id: 119, type: 'text', front: 'Treble clef (G clef)', back: 'Names the second line of the treble staff — used for higher notes' },
  // Level 1 additions
  { id: 120, type: 'text', front: '8va', back: 'Play eight notes (an octave) higher than written' },
  { id: 121, type: 'text', front: '8va or 8vb (below staff)', back: 'Play eight notes (an octave) lower than written' },
  { id: 122, type: 'text', front: 'Accidental', back: 'Sharps, flats, or naturals introduced apart from the key signature' },
  { id: 123, type: 'text', front: 'Crescendo / cresc.', back: 'Gradually getting louder' },
  { id: 124, type: 'text', front: 'Damper pedal', back: 'The pedal on the far right — depress and release' },
  { id: 125, type: 'text', front: 'Decrescendo / decresc.', back: 'Gradually getting softer' },
  { id: 126, type: 'text', front: 'Diminuendo / dim.', back: 'Gradually getting softer' },
  { id: 127, type: 'text', front: 'First and second endings', back: 'Play to the end of the first ending, repeat from repeat sign; on repetition skip the first ending and play the second' },
  { id: 128, type: 'text', front: 'Fortissimo (ff)', back: 'Very loud' },
  { id: 129, type: 'text', front: 'Mezzo forte (mf)', back: 'Moderately loud' },
  { id: 130, type: 'text', front: 'Mezzo piano (mp)', back: 'Moderately soft' },
  { id: 131, type: 'text', front: 'Pianissimo (pp)', back: 'Very soft' },
  { id: 132, type: 'text', front: 'Repetition', back: 'A compositional technique accomplished by repeating the same melodic patterns exactly' },
  { id: 133, type: 'text', front: 'Tenuto', back: 'Hold the note for its full value and/or emphasize it' },

  // ── TONALITY ──
  { id: 201, type: 'text', front: 'Half step', back: 'The smallest distance between two notes — from one key to the very next key on the piano' },
  { id: 202, type: 'text', front: 'Whole step', back: 'Two half steps — skips one key on the piano' },
  { id: 203, type: 'text', front: 'Sharp (#)', back: 'Raises a note by a half step' },
  { id: 204, type: 'text', front: 'Flat (♭)', back: 'Lowers a note by a half step' },
  { id: 205, type: 'text', front: 'Natural (♮)', back: 'Cancels a sharp or flat — returns the note to its original pitch' },
  { id: 206, type: 'text', front: 'Key signature', back: 'Sharps or flats at the beginning of each staff — tells you which notes are always sharp or flat' },
  { id: 207, type: 'text', front: 'C major scale', back: 'C D E F G A B C — no sharps or flats' },
  { id: 208, type: 'text', front: 'G major scale', back: 'G A B C D E F# G — one sharp (F#)' },
  { id: 209, type: 'text', front: 'D major scale', back: 'D E F# G A B C# D — two sharps (F#, C#)' },
  { id: 210, type: 'text', front: 'F major scale', back: 'F G A Bb C D E F — one flat (Bb)' },
  { id: 211, type: 'text', front: 'Major scale pattern', back: 'W W H W W W H (Whole Whole Half Whole Whole Whole Half)' },
  { id: 212, type: 'text', front: 'Lines of the treble staff (bottom to top)', back: 'E G B D F — Every Good Boy Does Fine' },
  { id: 213, type: 'text', front: 'Spaces of the treble staff (bottom to top)', back: 'F A C E — FACE' },
  { id: 214, type: 'text', front: 'Lines of the bass staff (bottom to top)', back: 'G B D F A — Good Boys Do Fine Always' },
  { id: 215, type: 'text', front: 'Spaces of the bass staff (bottom to top)', back: 'A C E G — All Cows Eat Grass' },
  { id: 216, type: 'text', front: 'Ledger line', back: 'A short line added above or below the staff for notes that go beyond the staff' },
  { id: 217, type: 'text', front: 'Middle C', back: 'The C between the treble and bass staves — first ledger line below treble, first ledger line above bass' },

  // ── INTERVALS ──
  { id: 301, type: 'text', front: 'Interval', back: 'The distance between two notes' },
  { id: 302, type: 'text', front: '2nd', back: 'An interval of one step — line to the next space, or space to the next line' },
  { id: 303, type: 'text', front: '3rd', back: 'An interval of one skip — line to line, or space to space' },
  { id: 304, type: 'text', front: '4th', back: 'An interval spanning 4 letter names — line to space skipping one, or space to line skipping one' },
  { id: 305, type: 'text', front: '5th', back: 'An interval spanning 5 letter names — line to line skipping one, or space to space skipping one' },
  { id: 306, type: 'text', front: '6th', back: 'An interval spanning 6 letter names' },
  { id: 307, type: 'text', front: '7th', back: 'An interval spanning 7 letter names' },
  { id: 308, type: 'text', front: 'Octave (8th)', back: 'An interval spanning 8 letter names — the same note name, one octave apart' },

  // ── TIME AND RHYTHM ──
  { id: 401, type: 'text', front: 'Time signature — top number', back: 'How many beats are in each measure' },
  { id: 402, type: 'text', front: 'Time signature — bottom number', back: 'What type of note gets one beat (4 = quarter note, 2 = half note, 8 = eighth note)' },
  { id: 403, type: 'text', front: '4/4 time', back: '4 beats per measure — quarter note gets one beat' },
  { id: 404, type: 'text', front: '3/4 time', back: '3 beats per measure — quarter note gets one beat' },
  { id: 405, type: 'text', front: '2/4 time', back: '2 beats per measure — quarter note gets one beat' },
  { id: 406, type: 'text', front: 'Whole note', back: '4 beats — open oval, no stem' },
  { id: 407, type: 'text', front: 'Half note', back: '2 beats — open oval with stem' },
  { id: 408, type: 'text', front: 'Quarter note', back: '1 beat — filled oval with stem' },
  { id: 409, type: 'text', front: 'Eighth note', back: '½ beat — filled oval with stem and flag' },
  { id: 410, type: 'text', front: 'Dotted half note', back: '3 beats — half note with a dot (dot adds half the note\'s value)' },
  { id: 411, type: 'text', front: 'Dotted quarter note', back: '1½ beats — quarter note with a dot' },
  { id: 412, type: 'text', front: 'Whole rest', back: 'Silence for 4 beats — hangs from a line (remember: whole rest is heavier, hangs down)' },
  { id: 413, type: 'text', front: 'Half rest', back: 'Silence for 2 beats — sits on top of a line (remember: half rest is like a hat, sits up)' },
  { id: 414, type: 'text', front: 'Quarter rest', back: 'Silence for 1 beat' },
  { id: 415, type: 'text', front: 'Eighth rest', back: 'Silence for ½ beat' },

  // ── CHORDS AND TRIADS ──
  { id: 501, type: 'text', front: 'Triad', back: 'A three-note chord built in 3rds — root, third, and fifth' },
  { id: 502, type: 'text', front: 'Root position', back: 'A triad with the root (bottom note) in the bass' },
  { id: 503, type: 'text', front: 'Tonic (I)', back: 'The first scale degree — the home base of the key' },
  { id: 504, type: 'text', front: 'Subdominant (IV)', back: 'The fourth scale degree' },
  { id: 505, type: 'text', front: 'Dominant (V)', back: 'The fifth scale degree — creates tension that wants to resolve to the tonic' },
  { id: 506, type: 'text', front: 'Primary triads', back: 'The I, IV, and V chords — the three most important chords in any key' },
  { id: 507, type: 'text', front: 'C major triad', back: 'C - E - G' },
  { id: 508, type: 'text', front: 'G major triad', back: 'G - B - D' },
  { id: 509, type: 'text', front: 'F major triad', back: 'F - A - C' },
  { id: 510, type: 'text', front: 'Major triad', back: 'A triad with a major 3rd on the bottom and a minor 3rd on top — sounds bright and stable' },
  { id: 511, type: 'text', front: 'Minor triad', back: 'A triad with a minor 3rd on the bottom and a major 3rd on top — sounds darker' },

  // ── EAR TRAINING ──
  { id: 601, type: 'text', front: 'Major five-finger pattern', back: 'Five adjacent notes starting on any key using the pattern W W H W — sounds bright' },
  { id: 602, type: 'text', front: 'Minor five-finger pattern', back: 'Five adjacent notes starting on any key using the pattern W H W W — sounds darker' },
  { id: 603, type: 'text', front: 'Legato', back: 'Smooth and connected — notes flow into each other without separation' },
  { id: 604, type: 'text', front: 'Forte vs. Piano (ear training)', back: 'Forte = loud | Piano = soft — ability to hear the difference between loud and soft dynamics' },
  { id: 605, type: 'text', front: 'Fortissimo (ff) vs. Pianissimo (pp)', back: 'Fortissimo = very loud | Pianissimo = very soft' },
]
